version: '2'

services:
  # nginx to serve static resources
  nginx:
    container_name: pfb_nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8000:8000
    networks:
      - app_net

  # database that preserves data
  postgresql:
    container_name: pfb_postgresql
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile
    environment:
      - POSTGRESQL_USER=benchmark
      - POSTGRESQL_PASSWORD=benchmark
      - POSTGRESQL_DATABASE=benchmark
    ports:
      - 5432:5432
    networks:
      - app_net

  # collection of python web frameworks to test
  frameworks:
    container_name: pfb_frameworks
    build:
      context: ./
      dockerfile: ./docker/frameworks/Dockerfile
    depends_on:
        - nginx
        - postgresql
    environment:
      - HTTP_HOST=pfb_nginx:8000
      - SQL_HOST=pfb_postgresql
    links:
      - nginx
      - postgresql
    ports:
      - 8080:8080
    networks:
      - app_net

  # controller to initalize and collect test results
#  controller:
#    container_name: pfb_controller
#    build:
#      context: ./
#      dockerfile: ./docker/controller/Dockerfile
#    depends_on:
#    - frameworks
#    environment:
#    - FRAMEWORK_HOST=pfb_frameworks:5000
#    links:
#    - frameworks
#    ports:
#    - 8080:8080
#    networks:
#    - app_net

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.101.0/24
          gateway: 192.168.101.1
