version: '2'

services:
  # nginx to serve static resources
  nginx:
    container_name: pfb-nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8000:8000
    networks:
      - app_net

  # database that preserves data
  postgresql:
    container_name: pfb-postgresql
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile
    environment:
      - POSTGRESQL_USER=benchmark
      - POSTGRESQL_PASSWORD=benchmark
      - POSTGRESQL_DATABASE=benchmark
      - POSTGRESQL_MAX_CONNECTIONS=500
    ports:
      - 5432:5432
    networks:
      - app_net

  # collection of python web frameworks to test
  frameworks:
    container_name: pfb-frameworks
    build:
      context: ./
      dockerfile: ./docker/frameworks/Dockerfile
    depends_on:
        - nginx
        - postgresql
    environment:
      - HTTP_HOST=pfb-nginx:8000
      - SQL_HOST=pfb-postgresql
      - TEST_HTTP_PORT=5000
    links:
      - nginx
      - postgresql
    ports:
      - 8001:8001
    networks:
      - app_net

  # controller to initalize and collect test results
  controller:
    container_name: pfb-controller
    build:
      context: ./
      dockerfile: ./docker/controller/Dockerfile
    depends_on:
    - frameworks
    environment:
    - TEST_HTTP_SERVER=pfb-frameworks
    - APP_HTTP_PORT=8001
    - TEST_HTTP_PORT=5000
    links:
    - frameworks
    ports:
    - 8002:8002
    networks:
    - app_net

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.101.0/24
          gateway: 192.168.101.1
