#!/bin/sh

set -e

POSTGRESQL_USER=${POSTGRESQL_USER:-"benchmark"}
POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-"benchmark"}
POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE:-"benchmark"}
POSTGRESQL_TEMPLATE=${POSTGRESQL_TEMPLATE:-"DEFAULT"}

# verify user premission are on the database
psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
  --CREATE DATABASE ${POSTGRESQL_DATABASE} OWNER ${POSTGRESQL_USER} TEMPLATE ${POSTGRESQL_TEMPLATE};
  --CREATE USER IF NOT EXISTS ${POSTGRESQL_USER} WITH SUPERUSER;
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRESQL_DATABASE} TO ${POSTGRESQL_USER};
  ALTER USER $POSTGRESQL_USER WITH PASSWORD '${POSTGRESQL_PASSWORD}';
EOSQL

# setup schema from dump.sql
psql -v ON_ERROR_STOP=1 --username ${POSTGRESQL_USER} -d ${POSTGRESQL_DATABASE} -a -f /tmp/dump.sql
